export const cars = [
  {
    brand: "Ford",
    model: "Mustang",
    type: "auto",
    id: "1",
    img: [
       "images/car/car2.png",
      "images/car/car1.webp",
      "images/car/car2.png"
    ],
    price: 641978,
    transmission: "Автомат",
    description: "Навигация, камера заднего вида, подогрев сидения",
    year: "2023 г.",
    motor: "2.3 л",
    motorType: "Бензин",
    mileage: 0,
    power: "317 л.с.",
    drive: "Задний",
    bodyType: "Купе",
    equipment: "Performance",
    color: "Белый",
    condition: "Не битый",
    guarantee: "Год"
  },
  {
    brand: "Ford",
    model: "Mustang",
    type: "auto",
    id: "1",
    img: [
       "images/car/car2.png",
      "images/car/car1.webp",
      "images/car/car2.png"
    ],
    price: 641978,
    transmission: "Автомат",
    description: "Навигация, камера заднего вида, подогрев сидения",
    year: "2019 г.",
    motor: "2.3 л",
    motorType: "Бензин",
    mileage: 88000,
    power: "317 л.с.",
    drive: "Задний",
    bodyType: "Купе",
    equipment: "Performance",
    color: "Белый",
    condition: "Не битый",
    guarantee: "Год"
  },
  {
    brand: "Ford",
    model: "Mustang",
    type: "bike",
    id: "1",
    img: [
       "images/car/car2.png",
      "images/car/car1.webp",
      "images/car/car2.png"
    ],
    price: 641978,
    transmission: "Автомат",
    description: "Навигация, камера заднего вида, подогрев сидения",
    year: "2023 г.",
    motor: "2.3 л",
    motorType: "Бензин",
    mileage: 8800,
    power: "317 л.с.",
    drive: "Задний",
    bodyType: "Купе",
    equipment: "Performance",
    color: "Белый",
    condition: "Не битый",
    guarantee: "Год"
  },
  {
    brand: "Ford",
    model: "Mustang",
    type: "auto",
    id: "1",
    img: [
       "images/car/car2.png",
      "images/car/car1.webp",
      "images/car/car2.png"
    ],
    price: 1641978,
    transmission: "Автомат",
    description: "Навигация, камера заднего вида, подогрев сидения",
    year: "2000 г.",
    motor: "2.3 л",
    motorType: "Бензин",
    mileage: 88000,
    power: "317 л.с.",
    drive: "Задний",
    bodyType: "Купе",
    equipment: "Performance",
    color: "Белый",
    condition: "Не битый",
    guarantee: "Год"
  },
  {
    brand: "Ford",
    model: "Mustang",
    type: "auto",
    id: "1",
    img: [
       "images/car/car2.png",
      "images/car/car1.webp",
      "images/car/car2.png"
    ],
    price: 10641978,
    transmission: "Автомат",
    description: "Навигация, камера заднего вида, подогрев сидения",
    year: "2023 г.",
    motor: "2.3 л",
    motorType: "Бензин",
    mileage: 88000,
    power: "317 л.с.",
    drive: "Задний",
    bodyType: "Купе",
    equipment: "Performance",
    color: "Белый",
    condition: "Не битый",
    guarantee: "Год"
  },
  {
    brand: "Ford",
    model: "Mustang",
    type: "auto",
    id: "1",
    img: [
      "images/car/car1.webp"
    ],
    price: 7000000,
    transmission: "Автомат",
    description: "ghjgj gjghjghj g jghjghj",
    year: "2023 г.",
    motor: "2.3 л",
    motorType: "Бензин",
    mileage: 88000,
    power: "317 л.с.",
    drive: "Задний",
    bodyType: "Купе",
    equipment: "Performance",
    color: "Белый",
    condition: "Не битый",
    guarantee: "Год"
  },
  {
    brand: "Ford",
    model: "Mustang",
    type: "auto",
    id: "1",
    img: [
       "images/car/car2.png",
      "images/car/car1.webp",
      "images/car/car2.png"
    ],
    price: 641978,
    transmission: "Автомат",
    description: "Навигация, камера заднего вида, подогрев сидения",
    year: "2023 г.",
    motor: "2.3 л",
    motorType: "Бензин",
    mileage: 88000,
    power: "317 л.с.",
    drive: "Задний",
    bodyType: "Купе",
    equipment: "Performance",
    color: "Белый",
    condition: "Не битый",
    guarantee: "Год"
  },
  {
    brand: "Toyota",
    model: "Mustang",
    type: "auto",
    id: "1",
    img: [
       "images/car/car2.png",
      "images/car/car1.webp",
      "images/car/car2.png"
    ],
    price: 641978,
    transmission: "Автомат",
    description: "Навигация, камера заднего вида, подогрев сидения",
    year: "2023 г.",
    motor: "2.3 л",
    motorType: "Бензин",
    mileage: 88000,
    power: "317 л.с.",
    drive: "Задний",
    bodyType: "Купе",
    equipment: "Performance",
    color: "Белый",
    condition: "Не битый",
    guarantee: "Год"
  }
]